#!/bin/bash

# Startup
echo "Scan Master Installation V.Linux-1.5"
echo "By: RafaTech Development"
echo ""

# Permissions
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
# No Permissions

echo "Installation must be run as root (sudo mode)"
echo "Installation Aborted."
echo "Please try again as root user."
exit
fi

# Remove old versions of the software
echo "Searching and deleting old versions of scanmaster..."
rm -rf /etc/scanmaster
rm -rf /usr/bin/scanmaster
echo ""

# Dependencies
echo "Installing dependencies..."
echo ""
apt install nmap gobuster figlet

# /etc/
echo ""
echo "Creating /etc/scanmaster..."
echo ""
cp -r etc/scanmaster /etc/

# CLI
echo "Installing CLI..."
cp scanmaster /usr/bin/

# End
echo ""
echo "Installation Finished."
echo "Thank you for choosing RafaTech Development."
echo "Launch ScanMaster using the command: 'scanmaster'"
echo ""
